import { Contact, Company, Lead, Deal, Task, Note, Activity } from '../src/types';

export function getSeedData(userId: string) {
  const companies: Company[] = [
    {
      id: 'comp-1',
      userId,
      name: 'Nexus Technologies',
      domain: 'nexustech.io',
      industry: 'Enterprise Software',
      size: '250-500',
      phone: '+1 (555) 234-5678',
      website: 'https://nexustech.io',
      address: '450 Mission Street, Suite 800',
      city: 'San Francisco',
      country: 'United States',
      annualRevenue: 45000000,
      createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    },
    {
      id: 'comp-2',
      userId,
      name: 'Apex BioHealth',
      domain: 'apexbiohealth.com',
      industry: 'Healthcare & Life Sciences',
      size: '100-250',
      phone: '+1 (555) 345-6789',
      website: 'https://apexbiohealth.com',
      address: '1200 Innovation Way',
      city: 'Boston',
      country: 'United States',
      annualRevenue: 28000000,
      createdAt: new Date(Date.now() - 25 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    },
    {
      id: 'comp-3',
      userId,
      name: 'CloudScale Infrastructure',
      domain: 'cloudscale.net',
      industry: 'Cloud Computing & DevOps',
      size: '50-100',
      phone: '+1 (555) 456-7890',
      website: 'https://cloudscale.net',
      address: '789 5th Ave',
      city: 'Seattle',
      country: 'United States',
      annualRevenue: 15000000,
      createdAt: new Date(Date.now() - 18 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    },
    {
      id: 'comp-4',
      userId,
      name: 'Meridian Global Logistics',
      domain: 'meridianlogistics.com',
      industry: 'Supply Chain & Logistics',
      size: '500-1000',
      phone: '+1 (555) 567-8901',
      website: 'https://meridianlogistics.com',
      address: '200 Riverfront Plaza',
      city: 'Chicago',
      country: 'United States',
      annualRevenue: 85000000,
      createdAt: new Date(Date.now() - 40 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    },
    {
      id: 'comp-5',
      userId,
      name: 'Vanguard FinTech Group',
      domain: 'vanguardfin.tech',
      industry: 'Financial Services',
      size: '100-250',
      phone: '+1 (555) 678-9012',
      website: 'https://vanguardfin.tech',
      address: '10 Wall Street',
      city: 'New York',
      country: 'United States',
      annualRevenue: 62000000,
      createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    },
  ];

  const contacts: Contact[] = [
    {
      id: 'cont-1',
      userId,
      name: 'Sarah Lin',
      email: 'sarah.lin@nexustech.io',
      phone: '+1 (555) 234-1101',
      title: 'VP of Engineering',
      companyId: 'comp-1',
      companyName: 'Nexus Technologies',
      status: 'customer',
      avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
      tags: ['Key Decision Maker', 'Enterprise', 'AI Champion'],
      source: 'Referral',
      lastContactedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
      createdAt: new Date(Date.now() - 28 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    },
    {
      id: 'cont-2',
      userId,
      name: 'Dr. Marcus Vance',
      email: 'm.vance@apexbiohealth.com',
      phone: '+1 (555) 345-2202',
      title: 'Chief Information Officer',
      companyId: 'comp-2',
      companyName: 'Apex BioHealth',
      status: 'lead',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      tags: ['Healthcare', 'HIPAA Priority', 'Budget Approved'],
      source: 'Inbound Demo',
      lastContactedAt: new Date(Date.now() - 4 * 86400000).toISOString(),
      createdAt: new Date(Date.now() - 22 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    },
    {
      id: 'cont-3',
      userId,
      name: 'Elena Rostova',
      email: 'elena@cloudscale.net',
      phone: '+1 (555) 456-3303',
      title: 'Head of Infrastructure & SecOps',
      companyId: 'comp-3',
      companyName: 'CloudScale Infrastructure',
      status: 'lead',
      avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
      tags: ['High Intent', 'Tech Evaluator'],
      source: 'Webinar Attendee',
      lastContactedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
      createdAt: new Date(Date.now() - 14 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    },
    {
      id: 'cont-4',
      userId,
      name: 'David Kim',
      email: 'dkim@meridianlogistics.com',
      phone: '+1 (555) 567-4404',
      title: 'Director of Procurement',
      companyId: 'comp-4',
      companyName: 'Meridian Global Logistics',
      status: 'customer',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      tags: ['Enterprise Account', 'Annual Contract'],
      source: 'Outbound Sales',
      lastContactedAt: new Date(Date.now() - 6 * 86400000).toISOString(),
      createdAt: new Date(Date.now() - 35 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 6 * 86400000).toISOString(),
    },
    {
      id: 'cont-5',
      userId,
      name: 'Chloe Bennett',
      email: 'c.bennett@vanguardfin.tech',
      phone: '+1 (555) 678-5505',
      title: 'VP of Product Operations',
      companyId: 'comp-5',
      companyName: 'Vanguard FinTech Group',
      status: 'lead',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      tags: ['Fintech', 'Urgent Timeline'],
      source: 'LinkedIn Sales Navigator',
      lastContactedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
      createdAt: new Date(Date.now() - 12 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    },
  ];

  const leads: Lead[] = [
    {
      id: 'lead-1',
      userId,
      name: 'Dr. Marcus Vance',
      email: 'm.vance@apexbiohealth.com',
      phone: '+1 (555) 345-2202',
      company: 'Apex BioHealth',
      title: 'Chief Information Officer',
      stage: 'Proposal',
      estimatedValue: 65000,
      source: 'Inbound Demo',
      score: 94,
      scoreReason: 'C-level sponsor with approved Q3 budget, evaluated competitor, and requested customized security compliance proposal.',
      aiSummary: 'Apex BioHealth needs an AI-enabled CRM layer to manage clinical trial partner outreach. High purchasing intent with strict HIPAA compliance mandate.',
      nextAction: 'Send revised BAA addendum and schedule security review call with Dr. Vance.',
      assignedTo: 'You',
      createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    },
    {
      id: 'lead-2',
      userId,
      name: 'Elena Rostova',
      email: 'elena@cloudscale.net',
      phone: '+1 (555) 456-3303',
      company: 'CloudScale Infrastructure',
      title: 'Head of Infrastructure',
      stage: 'Qualified',
      estimatedValue: 48000,
      source: 'Webinar Attendee',
      score: 87,
      scoreReason: 'Attended full product demo, downloaded API architecture whitepaper, high technical alignment.',
      aiSummary: 'Growing cloud platform looking to replace legacy spreadsheets with smart automated pipeline workflows for 40 account reps.',
      nextAction: 'Share ROI projection calculator and book sandbox walkthrough for team leads.',
      assignedTo: 'You',
      createdAt: new Date(Date.now() - 14 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    },
    {
      id: 'lead-3',
      userId,
      name: 'Chloe Bennett',
      email: 'c.bennett@vanguardfin.tech',
      phone: '+1 (555) 678-5505',
      company: 'Vanguard FinTech Group',
      title: 'VP of Product Operations',
      stage: 'Contacted',
      estimatedValue: 92000,
      source: 'LinkedIn Sales Navigator',
      score: 76,
      scoreReason: 'High enterprise value and clear problem statement, pending confirmation of Q4 procurement cycle.',
      aiSummary: 'Seeking to centralize high-net-worth investor relationships and deal lifecycle tracking with automated email reminders.',
      nextAction: 'Follow up with case study on financial services compliance and response time benchmarks.',
      assignedTo: 'You',
      createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    },
    {
      id: 'lead-4',
      userId,
      name: 'Julian Mercer',
      email: 'j.mercer@hyperflow.ai',
      phone: '+1 (555) 789-0123',
      company: 'HyperFlow Systems',
      title: 'Founder & CEO',
      stage: 'New',
      estimatedValue: 32000,
      source: 'Organic Search',
      score: 68,
      scoreReason: 'Early stage founder, submitted pricing enquiry, high engagement on blog.',
      aiSummary: 'Seed-stage startup looking for quick-to-adopt CRM with strong AI assistance capabilities for their 10-person team.',
      nextAction: 'Qualify lead timeline and budget availability on initial discovery call.',
      assignedTo: 'You',
      createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    },
    {
      id: 'lead-5',
      userId,
      name: 'Sarah Lin',
      email: 'sarah.lin@nexustech.io',
      phone: '+1 (555) 234-1101',
      company: 'Nexus Technologies',
      title: 'VP of Engineering',
      stage: 'Won',
      estimatedValue: 85000,
      source: 'Referral',
      score: 99,
      scoreReason: 'Contract signed for annual enterprise platform access.',
      aiSummary: 'Successfully closed 2-year partnership across engineering and partner development departments.',
      nextAction: 'Initiate kickoff onboarding and designate customer success liaison.',
      assignedTo: 'You',
      createdAt: new Date(Date.now() - 28 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    },
    {
      id: 'lead-6',
      userId,
      name: 'Gregory Paul',
      email: 'greg@legacyhardware.com',
      phone: '+1 (555) 890-1234',
      company: 'Legacy Hardware Co',
      title: 'Operations Manager',
      stage: 'Lost',
      estimatedValue: 18000,
      source: 'Cold Call',
      score: 32,
      scoreReason: 'Postponed digital transformation initiatives to next fiscal year due to internal reorg.',
      aiSummary: 'Interested in core product features but lacking executive budget signoff for modern cloud SaaS.',
      nextAction: 'Place in nurture campaign for Q1 check-in.',
      assignedTo: 'You',
      createdAt: new Date(Date.now() - 35 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 12 * 86400000).toISOString(),
    },
  ];

  const deals: Deal[] = [
    {
      id: 'deal-1',
      userId,
      title: 'Nexus Technologies Enterprise Expansion',
      value: 85000,
      stage: 'Closed Won',
      probability: 100,
      expectedCloseDate: new Date(Date.now() - 5 * 86400000).toISOString().split('T')[0],
      contactId: 'cont-1',
      contactName: 'Sarah Lin',
      companyId: 'comp-1',
      companyName: 'Nexus Technologies',
      aiInsights: 'Deal closed successfully at full list price with multi-year renewal options. Recommend immediate onboarding touchpoint.',
      createdAt: new Date(Date.now() - 25 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    },
    {
      id: 'deal-2',
      userId,
      title: 'Apex BioHealth Clinical Suite License',
      value: 65000,
      stage: 'Negotiation',
      probability: 80,
      expectedCloseDate: new Date(Date.now() + 12 * 86400000).toISOString().split('T')[0],
      contactId: 'cont-2',
      contactName: 'Dr. Marcus Vance',
      companyId: 'comp-2',
      companyName: 'Apex BioHealth',
      aiInsights: 'High probability of closing this month. Key friction point is data residency clause; offering the SOC2 package will expedite sign-off.',
      createdAt: new Date(Date.now() - 18 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    },
    {
      id: 'deal-3',
      userId,
      title: 'CloudScale DevOps Pipeline Integration',
      value: 48000,
      stage: 'Proposal',
      probability: 60,
      expectedCloseDate: new Date(Date.now() + 24 * 86400000).toISOString().split('T')[0],
      contactId: 'cont-3',
      contactName: 'Elena Rostova',
      companyId: 'comp-3',
      companyName: 'CloudScale Infrastructure',
      aiInsights: 'Technical validation complete. Elena requested proposal deck for upcoming executive committee meeting.',
      createdAt: new Date(Date.now() - 12 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    },
    {
      id: 'deal-4',
      userId,
      title: 'Vanguard Wealth Management Smart CRM Rollout',
      value: 92000,
      stage: 'Discovery',
      probability: 35,
      expectedCloseDate: new Date(Date.now() + 45 * 86400000).toISOString().split('T')[0],
      contactId: 'cont-5',
      contactName: 'Chloe Bennett',
      companyId: 'comp-5',
      companyName: 'Vanguard FinTech Group',
      aiInsights: 'Large potential upside ($92k). Multi-stakeholder review needed. Schedule executive briefing with Head of Wealth Management.',
      createdAt: new Date(Date.now() - 8 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    },
    {
      id: 'deal-5',
      userId,
      title: 'Meridian Logistics Fleet Sync Portal',
      value: 54000,
      stage: 'Closed Won',
      probability: 100,
      expectedCloseDate: new Date(Date.now() - 14 * 86400000).toISOString().split('T')[0],
      contactId: 'cont-4',
      contactName: 'David Kim',
      companyId: 'comp-4',
      companyName: 'Meridian Global Logistics',
      aiInsights: 'Annual subscription active and generating steady recurring ARR.',
      createdAt: new Date(Date.now() - 32 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 14 * 86400000).toISOString(),
    },
  ];

  const tasks: Task[] = [
    {
      id: 'task-1',
      userId,
      title: 'Send final contract & SOC2 report to Dr. Marcus Vance',
      description: 'Include legal review rider and BAA terms discussed during Tuesday call.',
      dueDate: new Date(Date.now() + 1 * 86400000).toISOString(),
      priority: 'high',
      status: 'pending',
      relatedType: 'deal',
      relatedId: 'deal-2',
      relatedName: 'Apex BioHealth Clinical Suite License',
      createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    },
    {
      id: 'task-2',
      userId,
      title: 'Schedule architecture alignment call with Elena Rostova',
      description: 'Prepare presentation deck covering webhook reliability and uptime SLA.',
      dueDate: new Date(Date.now() + 2 * 86400000).toISOString(),
      priority: 'high',
      status: 'pending',
      relatedType: 'lead',
      relatedId: 'lead-2',
      relatedName: 'Elena Rostova (CloudScale Infrastructure)',
      createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    },
    {
      id: 'task-3',
      userId,
      title: 'Prepare executive onboarding kickoff with Sarah Lin',
      description: 'Assign dedicated Customer Success engineer and configure workspace domains.',
      dueDate: new Date(Date.now() + 3 * 86400000).toISOString(),
      priority: 'medium',
      status: 'in_progress',
      relatedType: 'contact',
      relatedId: 'cont-1',
      relatedName: 'Sarah Lin',
      createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    },
    {
      id: 'task-4',
      userId,
      title: 'Quarterly review check-in with David Kim',
      description: 'Review system usage analytics and discuss seat expansion for Q4.',
      dueDate: new Date(Date.now() + 7 * 86400000).toISOString(),
      priority: 'low',
      status: 'pending',
      relatedType: 'deal',
      relatedId: 'deal-5',
      relatedName: 'Meridian Logistics Fleet Sync Portal',
      createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    },
    {
      id: 'task-5',
      userId,
      title: 'Run AI pipeline health audit for monthly executive summary',
      description: 'Generate pipeline conversion insights and top deal recommendations.',
      dueDate: new Date(Date.now() - 1 * 86400000).toISOString(),
      priority: 'medium',
      status: 'completed',
      relatedType: 'general',
      relatedName: 'Sales Pipeline Review',
      createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    },
  ];

  const notes: Note[] = [
    {
      id: 'note-1',
      userId,
      title: 'Apex BioHealth Security Audit Discussion',
      content: 'Dr. Vance confirmed that their InfoSec team requires data encryption at rest (AES-256) and automated audit logs. Offered our enterprise package which fulfills all specifications.',
      entityType: 'deal',
      entityId: 'deal-2',
      entityName: 'Apex BioHealth Clinical Suite License',
      tags: ['Security', 'InfoSec', 'Compliance'],
      createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    },
    {
      id: 'note-2',
      userId,
      title: 'Sarah Lin Feedback on Pilot Testing',
      content: 'Sarah reported that their sales reps saved an average of 4.5 hours per week using automated AI summaries and follow-up email drafts. Enthusiastic recommendation from management.',
      entityType: 'contact',
      entityId: 'cont-1',
      entityName: 'Sarah Lin',
      tags: ['Case Study', 'Product Feedback', 'ROI'],
      createdAt: new Date(Date.now() - 6 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 6 * 86400000).toISOString(),
    },
    {
      id: 'note-3',
      userId,
      title: 'Elena Rostova Migration Timeline',
      content: 'CloudScale is looking to migrate their legacy CRM database before the end of next month. Offered our automated one-click CSV & Supabase schema importer.',
      entityType: 'lead',
      entityId: 'lead-2',
      entityName: 'Elena Rostova (CloudScale Infrastructure)',
      tags: ['Migration', 'Urgent', 'Timeline'],
      createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    },
    {
      id: 'note-4',
      userId,
      title: 'SmartCRM Strategy: Focus on High-Value Opportunities',
      content: 'AI lead scoring has identified Apex BioHealth and CloudScale as top 2 closing priorities this quarter. Ensure executive alignment calls happen this week.',
      entityType: 'general',
      entityName: 'Team Strategy',
      tags: ['Strategy', 'Executive'],
      createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    },
  ];

  const activities: Activity[] = [
    {
      id: 'act-1',
      userId,
      type: 'deal_won',
      description: 'Closed Deal: Nexus Technologies Enterprise Expansion ($85,000)',
      entityType: 'deal',
      entityId: 'deal-1',
      entityName: 'Nexus Technologies Enterprise Expansion',
      createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    },
    {
      id: 'act-2',
      userId,
      type: 'stage_change',
      description: 'Advanced lead Dr. Marcus Vance from Qualified to Proposal stage',
      entityType: 'lead',
      entityId: 'lead-1',
      entityName: 'Dr. Marcus Vance (Apex BioHealth)',
      createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    },
    {
      id: 'act-3',
      userId,
      type: 'ai_analysis',
      description: 'AI generated Lead Score: 94/100 (Hot Lead) for Dr. Marcus Vance',
      entityType: 'lead',
      entityId: 'lead-1',
      entityName: 'Dr. Marcus Vance',
      createdAt: new Date(Date.now() - 2 * 86400000 + 3600000).toISOString(),
    },
    {
      id: 'act-4',
      userId,
      type: 'meeting',
      description: 'Held 45-minute technical deep dive with Elena Rostova regarding API sync',
      entityType: 'lead',
      entityId: 'lead-2',
      entityName: 'Elena Rostova',
      createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    },
    {
      id: 'act-5',
      userId,
      type: 'call',
      description: 'Discovery call completed with Chloe Bennett at Vanguard FinTech Group',
      entityType: 'contact',
      entityId: 'cont-5',
      entityName: 'Chloe Bennett',
      createdAt: new Date(Date.now() - 18 * 3600000).toISOString(),
    },
    {
      id: 'act-6',
      userId,
      type: 'task_completed',
      description: 'Completed Task: Run AI pipeline health audit for monthly executive summary',
      entityType: 'task',
      entityId: 'task-5',
      entityName: 'Pipeline Health Audit',
      createdAt: new Date(Date.now() - 12 * 3600000).toISOString(),
    },
    {
      id: 'act-7',
      userId,
      type: 'email',
      description: 'Sent follow-up email with pricing schedule to Julian Mercer',
      entityType: 'lead',
      entityId: 'lead-4',
      entityName: 'Julian Mercer',
      createdAt: new Date(Date.now() - 4 * 3600000).toISOString(),
    },
  ];

  return { companies, contacts, leads, deals, tasks, notes, activities };
}
